export const LOCALSTORAGE_KEYS = {
  lang: 'tonKristall-keyboard-lang',
};

export const TAGS = {
  div: 'div',
  header: 'header',
  main: 'main',
  h1: 'h1',
  textarea: 'textarea',
  footer: 'footer',
};

export const HEAD_APP = 'virtual keyboard';

export const KEYS_ITEMS = [
  [
    { en: { normal: '`', shift: '~' }, ru: { normal: 'Ё', shift: '' } },
    { en: { normal: '1', shift: '!' }, ru: { normal: '1', shift: '!' } },
    { en: { normal: '2', shift: '@' }, ru: { normal: '2', shift: '"' } },
    { en: { normal: '3', shift: '#' }, ru: { normal: '3', shift: '№' } },
    { en: { normal: '4', shift: '$' }, ru: { normal: '4', shift: ';' } },
    { en: { normal: '5', shift: '%' }, ru: { normal: '5', shift: '%' } },
    { en: { normal: '6', shift: '^' }, ru: { normal: '6', shift: ':' } },
    { en: { normal: '7', shift: '&' }, ru: { normal: '7', shift: '?' } },
    { en: { normal: '8', shift: '*' }, ru: { normal: '8', shift: '*' } },
    { en: { normal: '9', shift: '(' }, ru: { normal: '9', shift: '(' } },
    { en: { normal: '0', shift: ')' }, ru: { normal: '0', shift: ')' } },
    { en: { normal: '-', shift: '_' }, ru: { normal: '-', shift: '_' } },
    { en: { normal: '=', shift: '+' }, ru: { normal: '=', shift: '+' } },
    { en: { normal: 'Backspace' }, ru: { normal: 'Backspace' } },
  ],
  [
    { en: { normal: 'Tab' }, ru: { normal: 'Tab' } },
    { en: { normal: 'q' }, ru: { normal: 'й' } },
    { en: { normal: 'w' }, ru: { normal: 'ц' } },
    { en: { normal: 'e' }, ru: { normal: 'у' } },
    { en: { normal: 'r' }, ru: { normal: 'к' } },
    { en: { normal: 't' }, ru: { normal: 'е' } },
    { en: { normal: 'y' }, ru: { normal: 'н' } },
    { en: { normal: 'u' }, ru: { normal: 'г' } },
    { en: { normal: 'i' }, ru: { normal: 'ш' } },
    { en: { normal: 'o' }, ru: { normal: 'щ' } },
    { en: { normal: 'p' }, ru: { normal: 'з' } },
    { en: { normal: '[', shift: '{' }, ru: { normal: 'х', shift: '' } },
    { en: { normal: ']', shift: '}' }, ru: { normal: 'ъ', shift: '' } },
    { en: { normal: '\\', shift: '|' }, ru: { normal: '\\', shift: '/' } },
  ],
  [
    { en: { normal: 'CapsLock' }, ru: { normal: 'CapsLock' } },
    { en: { normal: 'a' }, ru: { normal: 'ф' } },
    { en: { normal: 's' }, ru: { normal: 'ы' } },
    { en: { normal: 'd' }, ru: { normal: 'в' } },
    { en: { normal: 'f' }, ru: { normal: 'а' } },
    { en: { normal: 'g' }, ru: { normal: 'п' } },
    { en: { normal: 'h' }, ru: { normal: 'р' } },
    { en: { normal: 'j' }, ru: { normal: 'о' } },
    { en: { normal: 'k' }, ru: { normal: 'л' } },
    { en: { normal: 'l' }, ru: { normal: 'д' } },
    { en: { normal: ';', shift: ':' }, ru: { normal: 'ж', shift: '' } },
    { en: { normal: `'`, shift: '"' }, ru: { normal: 'э', shift: '' } },
    { en: { normal: 'Enter' }, ru: { normal: 'Enter' } },
  ],
  [
    { en: { normal: 'Shift' }, ru: { normal: 'Shift' }, code: 'ShiftLeft' },
    { en: { normal: 'z' }, ru: { normal: 'я' } },
    { en: { normal: 'x' }, ru: { normal: 'ч' } },
    { en: { normal: 'c' }, ru: { normal: 'с' } },
    { en: { normal: 'v' }, ru: { normal: 'м' } },
    { en: { normal: 'b' }, ru: { normal: 'и' } },
    { en: { normal: 'n' }, ru: { normal: 'т' } },
    { en: { normal: 'm' }, ru: { normal: 'ь' } },
    { en: { normal: ',', shift: '<' }, ru: { normal: 'б', shift: '' } },
    { en: { normal: '.', shift: '>' }, ru: { normal: 'ю', shift: '' } },
    { en: { normal: '/', shift: '?' }, ru: { normal: '.', shift: ',' } },
    { en: { normal: '▲' }, ru: { normal: '▲' }, code: 'ArrowUp' },
    { en: { normal: 'Shift' }, ru: { normal: 'Shift' }, code: 'ShiftRight' },
  ],
  [
    { en: { normal: 'Ctrl' }, ru: { normal: 'Ctrl' }, code: 'ControlLeft' },
    { en: { normal: 'Win' }, ru: { normal: 'Win' }, code: 'MetaLeft' },
    { en: { normal: 'Alt' }, ru: { normal: 'Alt' }, code: 'AltLeft' },
    { en: { normal: ' ' }, ru: { normal: ' ' } },
    { en: { normal: 'Alt' }, ru: { normal: 'Alt' }, code: 'AltRight' },
    { en: { normal: 'Ctrl' }, ru: { normal: 'Ctrl' }, code: 'ControlRight' },
    { en: { normal: '◄' }, ru: { normal: '◄' }, code: 'ArrowLeft' },
    { en: { normal: '▼' }, ru: { normal: '▼' }, code: 'ArrowDown' },
    { en: { normal: '►' }, ru: { normal: '►' }, code: 'ArrowRight' },
  ],
];

export const TEXT_FOOTER = {
  system_info: 'Клавиатура создана в операционной системе Windows',
  change_lang: 'Комбинация для переключения языка: левый Alt + Ctrl',
};
