export const TAGS = {
  div: 'div',
  header: 'header',
  main: 'main',
  h1: 'h1'
};

export const HEAD_APP = 'virtual keyboard';

export const KEYS_ITEMS = [
  [
    { en: { normal: '`', shift: '~' }, ru: { normal: 'Ё' } },
    { en: { normal: '1', shift: '!' }, ru: { normal: '1', shift: '!' } },
    { en: { normal: '2', shift: '@' }, ru: { normal: '2', shift: '"' } },
    { en: { normal: '3', shift: '#' }, ru: { normal: '3', shift: '№' } },
    { en: { normal: '4', shift: '$' }, ru: { normal: '4', shift: ';' } },
    { en: { normal: '5', shift: '%' }, ru: { normal: '5', shift: '%' } },
    { en: { normal: '6', shift: '^' }, ru: { normal: '6', shift: ':' } },
    { en: { normal: '7', shift: '&' }, ru: { normal: '7', shift: '?' } },
    { en: { normal: '8', shift: '*' }, ru: { normal: '8', shift: '*' } },
    { en: { normal: '9', shift: '(' }, ru: { normal: '9', shift: '(' } },
    { en: { normal: '0', shift: ')' }, ru: { normal: '0', shift: ')' } },
    { en: { normal: '-', shift: '_' }, ru: { normal: '0', shift: '_' } },
    { en: { normal: '=', shift: '+' }, ru: { normal: '0', shift: '+' } },
    { en: { normal: 'Backspace' }, ru: { normal: 'Backspace' } },
  ],
  [
    { en: { normal: 'Tab' }, ru: { normal: 'Tab' } },
    { en: { normal: 'Q' }, ru: { normal: 'Й' } },
    { en: { normal: 'W' }, ru: { normal: 'Ц' } },
    { en: { normal: 'E' }, ru: { normal: 'У' } },
    { en: { normal: 'R' }, ru: { normal: 'К' } },
    { en: { normal: 'T' }, ru: { normal: 'Е' } },
    { en: { normal: 'Y' }, ru: { normal: 'Н' } },
    { en: { normal: 'U' }, ru: { normal: 'Г' } },
    { en: { normal: 'I' }, ru: { normal: 'Ш' } },
    { en: { normal: 'O' }, ru: { normal: 'Щ' } },
    { en: { normal: 'P' }, ru: { normal: 'З' } },
    { en: { normal: '[', shift: '{' }, ru: { normal: 'х', shift: 'Х' } },
    { en: { normal: ']', shift: '}' }, ru: { normal: 'ъ', shift: 'Ъ' } },
    { en: { normal: '\\', shift: '|' }, ru: { normal: '\\', shift: '/' } },
  ],
  [
    { en: { normal: 'Caps Lock' }, ru: { normal: 'Caps Lock' } },
    { en: { normal: 'A' }, ru: { normal: 'Ф' } },
    { en: { normal: 'S' }, ru: { normal: 'Ы' } },
    { en: { normal: 'D' }, ru: { normal: 'В' } },
    { en: { normal: 'F' }, ru: { normal: 'А' } },
    { en: { normal: 'G' }, ru: { normal: 'П' } },
    { en: { normal: 'H' }, ru: { normal: 'Р' } },
    { en: { normal: 'J' }, ru: { normal: 'О' } },
    { en: { normal: 'K' }, ru: { normal: 'Л' } },
    { en: { normal: 'L' }, ru: { normal: 'Д' } },
    { en: { normal: ';', shift: ':' }, ru: { normal: 'Ж' } },
    { en: { normal: `'`, shift: '"' }, ru: { normal: 'Э' } },
    { en: { normal: 'Enter' }, ru: { normal: 'Enter' } },
  ],
  [
    { en: { normal: 'Shift' }, ru: { normal: 'Shift' } },
    { en: { normal: 'Z' }, ru: { normal: 'Я' } },
    { en: { normal: 'X' }, ru: { normal: 'Ч' } },
    { en: { normal: 'C' }, ru: { normal: 'С' } },
    { en: { normal: 'V' }, ru: { normal: 'М' } },
    { en: { normal: 'B' }, ru: { normal: 'И' } },
    { en: { normal: 'N' }, ru: { normal: 'Т' } },
    { en: { normal: 'M' }, ru: { normal: 'Ь' } },
    { en: { normal: ',', shift: '<' }, ru: { normal: 'Б' } },
    { en: { normal: '.', shift: '>' }, ru: { normal: 'Ю' } },
    { en: { normal: '/', shift: '?' }, ru: { normal: '.', shift: ',' } },
    { en: { normal: '▲' }, ru: { normal: '▲' } },
    { en: { normal: 'Shift' }, ru: { normal: 'Shift' } },
  ],
  [
    { en: { normal: 'Ctrl' }, ru: { normal: 'Ctrl' } },
    { en: { normal: 'Win' }, ru: { normal: 'Win' } },
    { en: { normal: 'Alt' }, ru: { normal: 'Alt' } },
    { en: { normal: '' }, ru: { normal: '' } },
    { en: { normal: 'Alt' }, ru: { normal: 'Alt' } },
    { en: { normal: 'Ctrl' }, ru: { normal: 'Ctrl' } },
    { en: { normal: '◄' }, ru: { normal: '◄' } },
    { en: { normal: '▼' }, ru: { normal: '▼' } },
    { en: { normal: '►' }, ru: { normal: '►' } },
  ]
];